// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// resample_stratum
NumericMatrix resample_stratum(CharacterVector clusters, int B);
RcppExport SEXP surveybootstrap_resample_stratum(SEXP clustersSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    __result = Rcpp::wrap(resample_stratum(clusters, B));
    return __result;
END_RCPP
}
