# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resample_stratum <- function(clusters, B) {
    .Call('_surveybootstrap_resample_stratum', PACKAGE = 'surveybootstrap', clusters, B)
}

